// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj6CtmmB07GTjuLVYcLFBoOUoLHuQVn5s',
    appId: '1:323627399154:web:4f3f5b1cd9bb0053661d6b',
    messagingSenderId: '323627399154',
    projectId: 'phone-firebase-652d4',
    authDomain: 'phone-firebase-652d4.firebaseapp.com',
    storageBucket: 'phone-firebase-652d4.appspot.com',
    measurementId: 'G-205HSNZG58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWOdxIW6Y5brUZz6RMed68fbmRdIV1NHE',
    appId: '1:323627399154:android:c86679f160b43464661d6b',
    messagingSenderId: '323627399154',
    projectId: 'phone-firebase-652d4',
    storageBucket: 'phone-firebase-652d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYV7pkTJejCIA7MUS8z82nJ2SbICfcU_0',
    appId: '1:323627399154:ios:5c351fd1e3f5654c661d6b',
    messagingSenderId: '323627399154',
    projectId: 'phone-firebase-652d4',
    storageBucket: 'phone-firebase-652d4.appspot.com',
    iosBundleId: 'com.example.myFlutterOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYV7pkTJejCIA7MUS8z82nJ2SbICfcU_0',
    appId: '1:323627399154:ios:2de443f967868210661d6b',
    messagingSenderId: '323627399154',
    projectId: 'phone-firebase-652d4',
    storageBucket: 'phone-firebase-652d4.appspot.com',
    iosBundleId: 'com.example.myFlutterOtp.RunnerTests',
  );
}
